// Code generated by "stringer -type TokenType"; DO NOT EDIT.

package phpdoc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EOF-0]
	_ = x[Error-1]
	_ = x[Newline-2]
	_ = x[Whitespace-3]
	_ = x[Asterisk-4]
	_ = x[OpenDoc-5]
	_ = x[CloseDoc-6]
	_ = x[Backslash-7]
	_ = x[Query-8]
	_ = x[Lparen-9]
	_ = x[Rparen-10]
	_ = x[Lbrack-11]
	_ = x[Rbrack-12]
	_ = x[Lbrace-13]
	_ = x[Rbrace-14]
	_ = x[Lt-15]
	_ = x[Gt-16]
	_ = x[Comma-17]
	_ = x[Ellipsis-18]
	_ = x[Or-19]
	_ = x[And-20]
	_ = x[Array-21]
	_ = x[Ident-22]
	_ = x[Tag-23]
	_ = x[Var-24]
	_ = x[Other-25]
}

const _TokenType_name = "EOFErrorNewlineWhitespaceAsteriskOpenDocCloseDocBackslashQueryLparenRparenLbrackRbrackLbraceRbraceLtGtCommaEllipsisOrAndArrayIdentTagVarOther"

var _TokenType_index = [...]uint8{0, 3, 8, 15, 25, 33, 40, 48, 57, 62, 68, 74, 80, 86, 92, 98, 100, 102, 107, 115, 117, 120, 125, 130, 133, 136, 141}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
